### ISSUE TITLE
Litherite Block no spawn

### ISSUE THREAD

**Issue by lglare** [FTBTeam/FTB-Continuum#135] opened 2018-06-03 15:36 UTC
* **Modpack Version**: 1.1.0

* **Issue**: litherite block no spawn

* **Link to Log or Crash File Paste**: Not crash

* **Is it Repeatable?**: Repeatable

* **Mod/s Affected**: Environmental Tech / Advanced Rocketry

* **Known Fix**: dont know

I watched this thread -> https://github.com/FTBTeam/FTB-Continuum/issues/98
and happen same issue.

I used RFtools Builder with Shape quarry card for 160x160x80 area dig.
After all, I could not find it.
I feel it is too low spawn rate.
Is this not issue?

**Comment by Saereth** [comment] 2018-06-04 04:21
This is also happening on the stone bound server, mined out a massive area as above, not a single block started on version 1.0.2 now on version 1.10

**Comment by phit** [comment] 2018-06-04 08:21
okay, I reproduced this with just envtech and adv rocketry, though I believe advanced rocketry is not needed
and opened an issue https://github.com/zmaster587/AdvancedRocketry/issues/1325

**Comment by TotalHamman** [comment] 2018-06-04 15:00
Iglare and Saereth, can you please upload your planetDefs.xml file world save folder?  I am wanting to confirm that the oregen and artifact data was stripped from your save file as Phit described in his issue on the AR Github.

Single - packrootdirectory/saves/savename/advRocketry/planetDefs.xml
Server - packrootdirectory/worldname/advRocketry/planetDefs.xml

**Comment by phit** [comment] 2018-06-04 15:05
@TotalHamman Saereth is playing on my server, hence why I started looking into this in the first place. I could even reproduce it in a dev enviroment now, working on a PR to AR to fix it.
But here's the before and after if you are curious:

before: [planetDefs.xml.txt](https://github.com/FTBTeam/FTB-Continuum/files/2068792/planetDefs.xml)
after: [planetDefs.xml](https://github.com/FTBTeam/FTB-Continuum/files/2068788/planetDefs.xml.txt)

**Comment by tyler489** [comment] 2018-06-04 17:06
Mined out 6 chunks from 90-0 (yes i know it only appears from 4-80) and was unable to find one ore... Can confirm Litherite is suppost to spawn up to 64 times at 15 blocks each (960 blocks) per chunk MAX

**Comment by tyler489** [comment] 2018-06-05 18:12
AR dev has just pushed a fix to github

**Comment by aaronhowser1** [comment] 2018-06-10 17:54
Looks like the same is happening for all ET planets, not just Litherite. Not sure about other ore planets. If it's already fixed in dev that's good though.

**Comment by tyler489** [comment] 2018-06-10 23:51
Yeah its all ore planets on Servers

**Comment by tfox83** [comment] 2018-06-13 17:36
Fixed in 1.3.0 with latest AR update

**Comment by phit** [comment] 2018-06-13 17:37
its already fixed in 1.2.1

**Closed as completed by tfox83** 2018-06-13 17:36 UTC
