### ISSUE TITLE
Dye Mixer Laser Lens Missing

### ISSUE THREAD

**Issue by Tithonius** [FTBTeam/FTB-Continuum#255] opened 2018-06-21 06:45 UTC
* **Modpack Version**: 

* **Issue**:  The artificial dye mixer is a machine that is craft-able and you can do everything except get it to work. you can fill it with dye, you can do everything, but the laser lens that is normally crafted to go in the machine i cannot find in JEI or craft. Not sure if it got removed. but if it has, it would probably be a good idea to remove the dye mixer machine as well.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Industrial Foregoing

* **Known Fix**: Add the colored laser lens/remove dye mixer

**Comment by aaronhowser1** [comment] 2018-06-21 08:31
Duplicate of #215

**Closed as completed by aaronhowser1** 2018-06-21 08:31 UTC
Labels: duplicate
