### ISSUE TITLE
Infinite Heliumplasma

### ISSUE THREAD

**Issue by geary024** [FTBTeam/FTB-Continuum#308] opened 2018-07-07 07:17 UTC
* **Modpack Version**: 1.3.1

* **Issue**: Using the Fusion Control Computer, you can put Helium3 and Deuterium cells which creates Heliumplasma. If multiple cells are inputted, they are not consumed and the power generation cycle + Heliumplasma creation doesn't stop. 

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Yes. Tossing in two plus input cells and the cycle doesn't stop. If you put one a piece in, it consumes the input cells normally.

* **Mod/s Affected**: Tech Reborn

* **Known Fix**: Input one cell of each at a time

**Comment by aaronhowser1** [comment] 2018-07-07 07:18
Duplicate of #230

**Closed as completed by aaronhowser1** 2018-07-07 07:18 UTC
Labels: duplicate
