### ISSUE TITLE
Clockwork engine broken

### ISSUE THREAD

**Issue by TheGameGeek** [FTBTeam/FTB-Continuum#10] opened 2018-05-16 04:12 UTC
* **Modpack Version**: 1.0.0
* **Issue**: You cannot create the clockwork engine
* **link to image of the issue**: https://gyazo.com/4a88d315979afce18fac5fcde71dee5d
* **Is it Repeatable?**: yes just try to make a clockwork engine in the crafting table

**Comment by tfox83** [comment] 2018-05-16 04:15
Update to 1.0.1

Duplicate of #3

**Closed as completed by tfox83** 2018-05-16 04:15 UTC
Labels: duplicate
