### ISSUE TITLE
Unable to craft Large Lump of Galgador

### ISSUE THREAD

**Issue by Tandorius** [FTBTeam/FTB-Continuum#242] opened 2018-06-19 18:09 UTC
* **Modpack Version**: 1.2.1

* **Issue**: 
Galgadorian Block and Large Lump of Galgadorian have the same receipe (9 Galgadorian Metals)

JEI: 9 Galgadorian Metal = 1 Large Lump of Galgador / 1 Galgadorian Block
Crafting Table: 9 Galgadorian Metal = 1 Galgadorian Block

* **Link to Log or Crash File Paste**: 
https://imgur.com/a/ZLletnf

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: ProjectE

**Comment by alexsch01** [comment] 2018-06-19 20:51
I think you are wrong since the lump of galgadorian is different when smelted 

Lump of galgadorian doesn't equal galgadorian metal

Issue can be closed

**Comment by Tandorius** [comment] 2018-06-19 21:08
Did you have tested it? Please show with JEI under Galgorian Metal ... I posted also a screenshot ... thats the same Receipe ...

**Comment by alexsch01** [comment] 2018-06-19 21:21
did you use 9 lumps of galgadorian instead of galgorian metal?

**Comment by Tandorius** [comment] 2018-06-19 21:28
No, because JEI show only the receipe with Galgadorian Metal (Screenshot in my first post)

**Comment by aaronhowser1** [comment] 2018-06-19 21:30
The issue is that both things use the same recipe right?

**Comment by alexsch01** [comment] 2018-06-19 21:33
well it was fixed in 1.3.1 and 1.2.1 is beta now...

**Comment by Tandorius** [comment] 2018-06-19 21:33
Yes, thats the issue. Thanks.

**Comment by alexsch01** [comment] 2018-06-19 21:33
fixed already in 1.3.1

**Comment by alexsch01** [comment] 2018-06-19 21:33
![2018-06-19_17 32 57](https://user-images.githubusercontent.com/5721147/41625472-ef102c3a-73e6-11e8-81f5-0de2e3f702bf.png)

**Closed as completed** 2018-06-19 21:33 UTC
Labels: recipe issue, fixed in next version

**Comment by Tandorius** [comment] 2018-06-19 21:36
There are in the moment only beta versions available ... the latest release was 1.2.1 but it not available now.

Thank you for enlightment.

**Comment by Morganamilo** [comment] 2018-06-19 21:37
1.2.1 used to be listed as release. Hence #244.

**Comment by aaronhowser1** [comment] 2018-06-19 21:38
I think you can still download and install beta versions, just use the version button on the instance settings

**Comment by Morganamilo** [comment] 2018-06-19 21:39
Yeah that's what the betas are for. Just weird that they removed all the release listings.

**Comment by aaronhowser1** [comment] 2018-06-19 21:46
That was an accident, 1.3.1 was supposed to be set to release.

**Comment by Tandorius** [comment] 2018-06-21 13:24
Updated to version 1.3.1 ... the issue seems to persist in the latest version ... 
https://imgur.com/a/HuDOvBw

**Comment by alexsch01** [comment] 2018-06-21 13:26
Reinstall the pack 1.3.1 and see if that fixes it it worked for me
