### ISSUE TITLE
Liquid Dupe

### ISSUE THREAD

**Issue by TaterHog** [FTBTeam/FTB-Continuum#355] opened 2018-07-18 05:36 UTC
* **Modpack Version**:  1.4.1

* **Issue**:  I have a Pump Jack pumping oil into an IE fluid tank, that is filling the Distillation Tower, tank is staying empty, tower is processing faster. Put the 4 Crude Oil Cans from quest reward into Distillation Tower, it filled the tower up with 24 buckets and the cans don't get used, also the pump jack is running and no fluid was accumulating in the tank. Turned off Pump Jack, still have a continuously full Distillation Tower

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**: Remove the cans, everything is normal?

**Comment by aaronhowser1** [comment] 2018-07-18 15:24
Dupe of #108

**Closed as completed by aaronhowser1** 2018-07-18 15:24 UTC
Labels: bug, duplicate
