### ISSUE TITLE
Crusher does not work anymore

### ISSUE THREAD

**Issue by Maru467** [FTBTeam/FTB-Continuum#325] opened 2018-07-11 12:28 UTC
Version: 1.40 Beta

* **Issue:** 
Deleting and reforming the crusher has caused it to break. Even without power the crusher refuses to grind anything. I tried moving it as well, but it still doesn't work.

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Immersive engineering, presumably.

**Comment by aaronhowser1** [comment] 2018-07-11 12:50
Duplicate of #314

**Closed as completed by aaronhowser1** 2018-07-11 12:50 UTC
