### ISSUE TITLE
Cooking for Blockheads Counters uncraftable with Chisel Mod Blocks

### ISSUE THREAD

**Issue by eikotehmouse** [FTBTeam/FTB-Continuum#106] opened 2018-05-29 19:33 UTC
* **Modpack Version**: 1.1.0

* **Issue**: Can't craft Cooking For Blockhead's Kitchen Corner/ Counters with Chiseled Stone

* **Link to Log or Crash File Paste**:No crash to report 

* **Is it Repeatable?**:  Yes, make chiseled stone using the chisel and place into any crafting table to try to create Kitchen corner from Cooking for Blockheads

* **Mod/s Affected**:Chisel and Cooking for blockheads 

* **Known Fix**: currently only using stone works. But, JEI tells you that you can use Chisel Mod blocks

**Comment by BlayTheNinth** [comment] 2018-05-30 10:37
Works just fine for me, make sure you're using the actual Chiseled Stone blocks, not the Stone Bricks that the Chisel also lets you make from Stone. Also check that you're using un-dyed Terracotta.

**Comment by eikotehmouse** [comment] 2018-05-30 22:44
It's still a crafting discrepancy as JEI says you can use them, but you obviously can't.  So, this might go slightly deeper then just this. As for the flow of the mod pack, It would make you think that using chiseled stone would be way to go to get it. (because in jei it displays ever chisel mod stone under the sun before it shows vanilla)

**Comment by BlayTheNinth** [comment] 2018-05-30 23:04
JEI shows the Chiseled Stone blocks as usable, but not the Vanilla stone brick variants the Chisel also lets you make. The recipes JEI shows as usable can all be used for crafting.

![image](https://user-images.githubusercontent.com/1933180/40752114-7e664334-646e-11e8-8863-6d72968b1a3d.png)

Just trying to clear up that this is not a bug but rather a confusion caused by the Stone Chisel also making blocks that aren't actually in the `stone` ore dictionary. Only way to fix it would be replacing the recipes for the Cooking for Blockheads blocks to only accept `minecraft:stone`, instead of the ore dictionary `stone` in this pack.

**Comment by tfox83** [comment] 2018-05-31 17:38
Thanks @blay09 going to close this issue.

**Closed as completed by tfox83** 2018-05-31 17:38 UTC
