### ISSUE TITLE
Iridium Ore in Industrial Grinder

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#58] opened 2018-05-21 06:07 UTC
* **Modpack Version**: 1.0.2
* **Issue**: 
When putting Iridium Ore into the TR Industrial Grinder it yields 1 Ingot (not Dust) and 2 small piles of platinum dust.
Iridium can be "ore doubled" via the TR Grinder and the IE Crusher, both of which are considerably lower tech level.
If for some reason, that I can not yet see, the Industrial Grinder is not supposed to double the Iridium then surely it should still output it in its dust form.

**Comment by Xavion3** [comment] 2018-05-21 13:11
This is caused by some mod interactions, by default in tech reborn you can only process iridium ore in the industrial grinder for the one ingot. Due to other mods adding iridium ore and compat abounding it gets the doubling recipes.

Tech Reborn's intended progression is get the rare ores at 1 ingot each to get enough to get UU matter to start producing it yourself I believe, this pack twists that a bit but results in some oddities like this as a result.

**Comment by tfox83** [comment] 2018-05-23 18:24
Going to have @modmuss50 take a look at this:
I tried this and it doesn't remove or add the recipe:
```
mods.techreborn.industrialGrinder.removeInputRecipe(<thermalfoundation:ore:7>);
mods.techreborn.industrialGrinder.addRecipe(<thermalfoundation:material:135> * 2, <techreborn:smalldust:38> * 2, null, null, <thermalfoundation:ore:7>, <liquid:water> * 1000, 300, 40);
```

**Comment by modmuss50** [comment] 2018-05-24 10:11
@tfox83 adding recipes seems to work fine, let me know if its still broken in the full pack and ill take another look.

![screen shot 2018-05-24 at 11 06 45](https://user-images.githubusercontent.com/4324090/40479054-9254327e-5f42-11e8-88c8-df10165b916a.png)

As for removing this recipe you need to use the ore dict name (as the recipe was registed using the ore dict name, im not sure why crafttweaker isnt saying they match (Code: https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/compat/crafttweaker/CTGeneric.java#L108). 

But when testing using the following:

`mods.techreborn.industrialGrinder.removeInputRecipe(<ore:oreIridium>);`

removing the recipe seems to work just fine, and provides the above uses for iridium ore. I can look into making the removal a bit more lenient when checking if the inputs are equal.

**Comment by modmuss50** [comment] 2018-05-24 10:18
Also, that example recipe you provided has a slight issue causing the fluid to not be used.

`mods.techreborn.industrialGrinder.addRecipe(<thermalfoundation:material:135> * 2, <techreborn:smalldust:38> * 2, null, null, <thermalfoundation:ore:7>, null, <liquid:water> * 1000, 300, 40);`

Works, note the extra null for the 2nd input, as before it was trying to use the fluid on the 2nd input slot, but now this uses the other method that uses the fluid tank.

**Comment by Kuktar** [comment] 2018-05-24 10:33
ModmusModmuss50 do you have a patreon. I would love to buy you a cup of
coffee each month

**Comment by modmuss50** [comment] 2018-05-24 10:35
No, I dont @Kuktar best thing you can do it just enjoy the mod 👍

**Comment by Kuktar** [comment] 2018-05-24 11:01
I thoroughly enjoy it! Thank you for all your hard work.

**Comment by tfox83** [comment] 2018-05-24 18:29
Ok great, thanks Modmuss, ill get those changes into the next dev version and let you know if I have anymore problems.

**Comment by tfox83** [comment] 2018-05-31 19:05
Fixed in next version 
![image](https://user-images.githubusercontent.com/4246308/40802612-f11a93ce-64ca-11e8-9558-cf938f2dd782.png)

**Closed as completed by tfox83** 2018-05-31 19:05 UTC
Labels: submitted to moddev, recipe issue
