### ISSUE TITLE
The Eye of the Storm artifacts

### ISSUE THREAD

**Issue by Yonoshix** [FTBTeam/FTB-Continuum#272] opened 2018-06-25 15:28 UTC
* **Modpack Version**: 1.3.1

* **Issue**: the artifacts of the "The Eye of the Storm" planet are wrong in the questbook. In the planetDefs.xml it says you need Charcoal, fire charge, flux, Lavawood and charred nether bricks. In the Questbook: Coal, fire charge, flux, Firewood and charred nether bricks.
https://prnt.sc/jz5nx9
https://prnt.sc/jz5o6w

* **Is it Repeatable?**: yes

* **Mod/s Affected**: advanced rocketry

* **Known Fix**: just take the 1 form the minecraft:coal 1 and put it to the tconstruct:firewood

**Comment by aaronhowser1** [comment] 2018-06-25 15:31
Duplicate of #219 and #220, fixed in next version

**Closed as completed by aaronhowser1** 2018-06-25 15:31 UTC
Labels: duplicate, quests issue, fixed in next version
