### ISSUE TITLE
Infinite crude oil in rhe distillation tower, while using cans from forestry

### ISSUE THREAD

**Issue by Galluno** [FTBTeam/FTB-Continuum#276] opened 2018-06-26 20:00 UTC
**Modpack Version**: 1.3.1

**Issue**: The Oil can from Forestry, given as a reward from a quest, when put in the distillation tower, gives infinite crude oil

**Link to Log or Crash File Paste**: No crash, but I recorded a video of the bug: https://youtu.be/FPPpfnrbAq8

**Is it Repeatable?**: I don't know, only tested in my World

**Mod/s Affected**: Forestry, Immersive Engineering

**Known Fix**: No known fix atm

**Comment by aaronhowser1** [comment] 2018-06-26 20:01
Duplicate of #108

**Closed as completed by aaronhowser1** 2018-06-26 20:01 UTC
Labels: duplicate
