### ISSUE TITLE
Flux Points slowly corrupt chunks.

### ISSUE THREAD

**Issue by ZeekDaGeek** [FTBTeam/FTB-Continuum#379] opened 2018-07-25 10:58 UTC
* **Modpack Version**: FTB Continuum 1.4.1

* **Issue**: Flux points will slowly corrupt chunks when left in unloaded chunks for a long period of time. Eventually no player can visit the chunks without being disconnect by a "NBT too big" error.

* **Link to Log or Crash File Paste**:  Additional information can be found on this issue: https://github.com/SonarSonic/Flux-Networks/issues/252

* **Is it Repeatable?**: Yes, it's happened to a number of bases.

* **Mod/s Affected**: Flux Network

* **Known Fix**: Updating Flux Networks to the next version will fix the problem.

**Comment by HDR** [comment] 2018-07-26 20:34
For anyone that wants a quick fix until the issue is resolved, https://github.com/MrHDR/Flux-Networks compile that and upload it on your server and flux networks will work as intended.

**Comment by DerSoftwerker** [comment] 2018-08-05 16:53
Flux Network and Sonar Core has a new Version released already. I have updated my server and can confirm the problem is resolved.

**Comment by tfox83** [comment] 2018-09-17 14:35
Fixed in  1.5.0 Beta

**Closed as completed by tfox83** 2018-09-17 14:35 UTC
Labels: fixed in mod update
