### ISSUE TITLE
 A fatal error has occurred, this connection is terminated

### ISSUE THREAD

**Issue by VexaBoops** [FTBTeam/FTB-Continuum#28] opened 2018-05-17 17:36 UTC
every time i connect to my server it will log into the server but a frame later will disconnect me with this error every time: A fatal error has occurred, this connection is terminated the friend i play with can connect and play. this started after he when in to the nether once so i have uninstalled both pack and server multiple times

* **Modpack Version**: 1.0.2
* **Issue**: Can connect to my server but others can

server log: https://paste.feed-the-beast.com/view/4408e11a

Client log: https://paste.feed-the-beast.com/view/d969ba4e

**Comment by 016Nojr** [comment] 2018-05-17 17:54
Duplicate of #14

**Closed as completed** 2018-05-17 17:54 UTC
Labels: duplicate
