### ISSUE TITLE
Problem connecting to server because of MineTogether

### ISSUE THREAD

**Issue by tjsd** [FTBTeam/FTB-Continuum#14] opened 2018-05-16 08:37 UTC
* **Modpack Version**: v1.0.1

* **Issue**: User times out constantly and server reports issues with mine together mod

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/afba637e

* **Is it Repeatable?**:  I see the same in the log when everyone connects, but depending on the connection to the server if it times people out or not.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Xavion3** [comment] 2018-05-16 09:52
To elaborate a bit as this was happening to me, I tried several times to connect, restarted minecraft multiple times, and tried setting the game's timeout to 15 minutes. None of them seemed to help, eventually it started working out of nowhere, and the first time it disconnected me with the same error after a second but after the first time I made it it seems to be working perfectly every time.

**Comment by ren-** [comment] 2018-05-16 10:37
Same here. Magically working, but occasionally players are timing out because of this.

**Comment by tfox83** [comment] 2018-05-16 14:57
I have forward this over to the Creeperhost team so they can look into this.

**Comment by Cloudhunter** [comment] 2018-05-16 15:06
Thanks for the report - looking into it now. Not quite sure HOW it is happening, but we'll see!

**Comment by ren-** [comment] 2018-05-16 15:24
Additional information, I am not using Creeperhost. Not sure about @tjsd

**Comment by Xavion3** [comment] 2018-05-16 15:25
Same for us, just a private server with a few people on it.

**Comment by Cloudhunter** [comment] 2018-05-16 17:00
I've looked into it a bit, and I'm 99% sure that the timeout issue isn't actually anything to do with MineTogether - it just throws an error about the same time it happens - caused by a forge change https://github.com/MinecraftForge/MinecraftForge/pull/4890. It's a good change - it was technically a bug in the code, but it wasn't affecting anything as I only use one packet type.

I've done a quick build which SHOULD stop this error at least (I sadly cannot even get the error to show up myself in my development environment). Can you test it out and let me know?

https://transfer.sh/xuPgD/minetogether-1.10.2-1.8.7.jar

Long term (next proper build) I won't send anything on login at all in order to avoid anything in MineTogether even potentially causing this issue.

**Comment by ren-** [comment] 2018-05-16 17:03
Maybe the hosting environment affects it? I tried to host another pack and this time the timout issue is related to: https://gist.github.com/ren-/9dc484fbf718fec3ac642d53a06895f4

**Comment by Kuktar** [comment] 2018-05-17 01:40
This is also happening to me periodicaly. I just have me and 5 other people on a home private server. If it matters to test i removed mine together and it still did it randomly. after the timeout it almost always lets players reconnect.

**Comment by Cloudhunter** [comment] 2018-05-17 12:43
Seems as I thought it isn't a MineTogether issue then. Can you try the build and see if it at least removes the error message in the log about it?

**Comment by tfox83** [comment] 2018-05-23 19:15
I have had quite a few people including myself try and reproduce this on multiple servers and we are not able to reproduce.  I am closing this issue for now, if I get more reports or can reproduce this I will reopen.

**Closed as completed by tfox83** 2018-05-23 19:15 UTC
Labels: bug
