### ISSUE TITLE
Server crashing (Ticking entity error) when extracting liquids with cells from tree fluid extractor

### ISSUE THREAD

**Issue by DerSoftwerker** [FTBTeam/FTB-Continuum#87] opened 2018-05-25 13:17 UTC
* **Modpack Version**: 1.0.2

* **Issue**: Server crashing (Ticking entity error) when extracting liquids with cells from tree fluid extractor

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/59c0770f

* **Is it Repeatable?**: Not tried, live environment. When issue occurs, the server will be in a crash loop

* **Mod/s Affected**: Tech reborn

* **Known Fix**: Forge.cfg - remove erroring entities true

**Comment by Valerate** [comment] 2018-05-26 14:50
Can confirm, Server is now stuck on crash loop.
The error I got when the server died was "[java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded!](https://pastebin.com/yhHqhuPZ)" I stood next to the machine so I doubt it wasn't loaded. .
My Added mods; Millenaire, Minecolonies, neither which I've used much, and Infernal Monsters.
At the time of the crash I was removing a cell of Latex from the machine and the other person on the server was exploring.

Addition: I managed to not crash it once, but it consumed everything inside (8000mb) and only gave me 1 cell

**Comment by tfox83** [comment] 2018-05-26 16:41
Hmm interesting, @modmuss50 mind taking a look at this when you have some time.  Not sure whos end it is on.

**Comment by modmuss50** [comment] 2018-05-26 17:00
This has been fixed by both of us. And FE has improved their fluid handling to fix some of the issues with it. @DerSoftwerker I believe modpack version 1.1.0 has the fixes in.

Also a duplicate of #52

**Closed as completed** 2018-05-26 18:47 UTC
