### ISSUE TITLE
Eucalyptus planks to sticks got overlooked for the nerf.  craft gives 4 sticks not 2

### ISSUE THREAD

**Issue by OldManShorty** [FTBTeam/FTB-Continuum#43] opened 2018-05-19 09:22 UTC
* **Modpack Version**: 1.0.2
* **Issue**: when crafting stick from eucalyptus planks you get 4 sticks instead of 2

* **Link to Log or Crash File Paste**: No crashes

* **Is it Repeatable?**: Yes everytime

* **Mod/s Affected**: n/a

* **Known Fix**: change the recipe lol

**Comment by tfox83** [comment] 2018-05-21 18:47
Duplicate of #35

**Closed as completed** 2018-05-21 18:48 UTC
Labels: duplicate
