### ISSUE TITLE
Good Morning! #288

### ISSUE THREAD

**Issue by NassiC** [FTBTeam/FTB-Continuum#263] opened 2018-06-22 18:05 UTC
* **Modpack Version**: 1.3.1

* **Issue**: The Quest "Good Morning #288, has no task, so it auto completes when it is unlocked.
It looks like its meant to be a queast to make the projecte Morningstar, but it is missing the task.

**Comment by aaronhowser1** [comment] 2018-06-23 03:05
Duplicate of #233, fixed in dev

**Closed as completed by aaronhowser1** 2018-06-23 03:05 UTC
Labels: duplicate, quests issue, fixed in next version
